# 机器人配置文件
robot:
  # 主机械臂配置
  master:
    ip: "192.168.1.19"
    port: 8080
    name: "master_robot"
    arm_init_joints: [0, 0, 90, 0, 90, 0]  # 机械臂6个关节的初始角度

    
  # 从机械臂配置
  slave:
    ip: "192.168.1.18"
    port: 8080
    name: "slave_robot"
    arm_init_joints: [0, 0, 90, 0, 90, 0]  # 机械臂6个关节的初始角度

    
  # 手部控制配置
  hand:
    # 抓取角度配置
    grip_angles: [1000, 14000, 14000, 14000, 14000, 10000]
    release_angles: [4000, 17800, 17800, 17800, 17800, 10000]
    
   