robot:
  # 网络配置
  ip: "192.168.1.18"
  port: 8080
  
  # 位置调整参数 [安全预备位置偏移, 最终抓取位置偏移]
  adjustment: [0.0, 0.0]
  
  # 机械臂关节配置
  arm_init_joints: [0, 0, 90, 0, 90, 0]  # 机械臂6个关节的初始角度
  arm_move_speed: 20  # 机械臂运动速度，单位%，范围 1~100
  arm_fang_joints: [-90, 0, 90, 0, 90, 0]  # 机械臂放物关节角度
  
  # 灵巧手配置
  grip_angles: [1000, 14000, 14000, 14000, 14000, 10000]  # 灵巧手抓取角度配置
  release_angles: [4000, 17800, 17800, 17800, 17800, 10000]  # 灵巧手释放角度配置 